-
  - 正常登录
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    headers:
    type: data
    body:
      username: admin
      password: '123456.'
      verificationCode: 99999
      loginStatus: 0

-
  - 账号错误登录
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    headers:
    type: data
    body:
      username: admi
      password: '123456.'
      verificationCode: 99999
      loginStatus: 0
-
  - 密码错误登录
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    headers:
    type: data
    body:
      username: admin
      password: '123456'
      verificationCode: 99999
      loginStatus: 0
-
  - 验证码错误登录
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    headers:
    type: data
    body:
      username: admin
      password: '123456.'
      verificationCode: 9999
      loginStatus: 0
-
  - 正常登录
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    headers:
    type: data
    body:
      username: admin
      password: '123456.'
      verificationCode: 99999
      loginStatus: 0
-
  - 正常登录
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    headers:
    type: data
    body:
      username: admin
      password: '123456.'
      verificationCode: 99999
      loginStatus: 0
-
  - 正常登录11111111
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    headers:
    type: data
    body:
      username: admin
      password: '123456.'
      verificationCode: 99999
      loginStatus: 0
-
  - 正常登录222222
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    headers:
    type: data
    body:
      username: admin
      password: '123456.'
      verificationCode: 99999
      loginStatus: 0
-
  - 正常登33333
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    headers:
    type: data
    body:
      username: admin
      password: '123456.'
      verificationCode: 99999
      loginStatus: 0
-
  - 正常登4444444
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    headers:
    type: data
    body:
      username: admin
      password: '123456.'
      verificationCode: 99999
      loginStatus: 0
-
  - 正常登555555
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    headers:
    type: data
    body:
      username: admin
      password: '123456.'
      verificationCode: 99999
      loginStatus: 0
-
  - 正常登6666666
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    headers:
    type: data
    body:
      username: admin
      password: '123456.'
      verificationCode: 99999
      loginStatus: 0
-
  - 正常登777777777
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    headers:
    type: data
    body:
      username: admin
      password: '123456.'
      verificationCode: 99999
      loginStatus: 0
