-
  - 正常登录
  -
    method: post
    url: http://account-admin-webos-test.lastmiles.cn/account-admin-web/login
    heards:
    type:
    body: "username:admin,password:123456.,verificationCode:99999,loginStatus:0"

